### ISSUE TITLE
Options for Write VTK File (Rectilinear Grid) 

### ISSUE THREAD

**Issue by mwpriddy** [dream3d/DREAM3D#208]
In the updated version, there are no longer options for selecting data to be written to VTK file format.  The only data written to the VTK file format are the FeatureIDs.  

It does seem adding this functionality is in the works because the manual calls for multiple Boolean operators for writing Euler angles, phase, etc. 

http://dream3d.bluequartz.net/Documentation/DREAM3D/vtkrectilineargridwriter.html

Thanks!

**Comment by sdonegan** [comment]
Closing as duplicates of other open issues and with the implementation of the AbaqusHexahedron writer.
