### ISSUE TITLE
Most filters do not check array sizes for compatibility

### ISSUE THREAD

**Issue by wlenthe** [dream3d/DREAM3D#230]
If a filter takes 2 or more arrays as input it often assumes they belong to the same attribute matrix. For example Generate IPF Colors requires both Cell Phases and Cell Euler angles. The existence of the arrays is checked in preflight but not their sizes / parent attribute matrix.  At runtime the size of Euler Angles is used to determine the number of points. If the user selects Cell Euler angles and Feature Phases the filter will preflight correctly but at runtime it will crash when it tries to access an element of the Phase array that is greater than the number of features but smaller than the number of voxels. Filters anticipating multiple arrays from the same attribute matrix should check that that is the case during preflight (or add a similar precaution)

**Comment by sdonegan** [comment]
The plan is to address this issue as filters are reviewed for the upcoming v5 release.  All arrays that require tuple/dimension compatibility should be looked for up to at least their parent AttributeMatrix.  If the arrays also require a geometry compatibility, they need to be checked up to their parent DataContainer.  In future designs, the hope is to abstract dataChecking to be based on the filter parameters themselves; for now, the onus is on the developer of any new filter the ensure they validate tuple/dimension compatibility if requiring multiple input arrays.

**Comment by imikejackson** [comment]
Here is a list of filters from most of the plugins that we are aware of that have 2 or more DataArrayPaths as filter parameters. Not sure if they all have the issue or not, but they all need to be checked.


| Plugin | Filter | Count |
|--------|--------|-------|
| Core | CopyFeatureArrayToCellArray | 2 | 
| Core | CreateFeatureArrayFromCellArray | 2 | 
| DictionaryIndexingPlugin | CalculateMeanInnerProducts | 3 | 
| GenericPlugin | ConvertOrientations | 6 | 
| GenericPlugin | FindBoundingBoxFeatures | 3 | 
| GenericPlugin | FindCellQuats | 3 | 
| GenericPlugin | FindFeaturePhases | 2 | 
| GenericPlugin | FindFeaturePhasesBinary | 2 | 
| GenericPlugin | GenerateVectorColors | 2 | 
| ImageProcessingPlugin | GrayToRGB | 3 | 
| ImageProcessingPlugin | ImageCalculator | 2 | 
| IOPlugin | GBCDTriangleDumper | 4 | 
| IOPlugin | INLWriter | 5 | 
| IOPlugin | LosAlamosFFTWriter | 3 | 
| IOPlugin | SurfaceMeshToNodesTrianglesEdges | 2 | 
| IOPlugin | SurfaceMeshToNonconformalVtk | 2 | 
| IOPlugin | SurfaceMeshToStl | 2 | 
| IOPlugin | SurfaceMeshToVtk | 2 | 
| OrientationAnalysisPlugin | GenerateEulerColors | 4 | 
| OrientationAnalysisPlugin | GenerateIPFColors | 4 | 
| OrientationAnalysisPlugin | GenerateMisorientationColors | 4 | 
| OrientationAnalysisPlugin | GenerateRodriguesColors | 4 | 
| OrientationAnalysisPlugin | WritePoleFigure | 4 | 
| OrientationAnalysisPlugin | WriteStatsGenOdfAngleFile | 3 | 
| ProcessingPlugin | BadDataNeighborOrientationCheck | 4 | 
| ProcessingPlugin | FillBadData | 2 | 
| ProcessingPlugin | MinNeighbors | 3 | 
| ProcessingPlugin | MinSize | 3 | 
| ProcessingPlugin | NeighborOrientationCorrelation | 4 | 
| ProcessingPlugin | RemoveFlaggedFeatures | 2 | 
| ProcessModelingPlugin | PrincipalComponentAnalysis | 3 | 
| ProcessModelingPlugin | Silhouette | 2 | 
| ReconstructionPlugin | AlignSectionsMisorientation | 4 | 
| ReconstructionPlugin | AlignSectionsMutualInformation | 4 | 
| ReconstructionPlugin | CAxisSegmentFeatures | 4 | 
| ReconstructionPlugin | EBSDSegmentFeatures | 4 | 
| ReconstructionPlugin | GroupMicroTextureRegions | 7 | 
| ReconstructionPlugin | IdentifyMicroTextureRegions | 3 | 
| ReconstructionPlugin | MergeColonies | 6 | 
| ReconstructionPlugin | MergeTwins | 5 | 
| ReconstructionPlugin | ScalarSegmentFeatures | 2 | 
| ReconstructionPlugin | SineParamsSegmentFeatures | 2 | 
| ReconstructionPlugin | VectorSegmentFeatures | 2 | 
| SamplingPlugin | ExtractFlaggedFeatures | 2 | 
| StatisticsPlugin | CorrelateValuesWithVectorDirection | 2 | 
| StatisticsPlugin | FindAvgCAxes | 2 | 
| StatisticsPlugin | FindAvgOrientations | 4 | 
| StatisticsPlugin | FindAvgScalarValueForFeatures | 2 | 
| StatisticsPlugin | FindBasalLoadingFactor | 3 | 
| StatisticsPlugin | FindBoundaryStrengths | 4 | 
| StatisticsPlugin | FindDirectionalModuli | 4 | 
| StatisticsPlugin | FindEllipsoidError | 5 | 
| StatisticsPlugin | FindFeatureClustering | 4 | 
| StatisticsPlugin | FindFeatureHistogram | 3 | 
| StatisticsPlugin | FindFeatureNeighborCAxisMisalignments | 4 | 
| StatisticsPlugin | FindFeatureReferenceCAxisMisorientations | 4 | 
| StatisticsPlugin | FindFeatureReferenceMisorientations | 6 | 
| StatisticsPlugin | FindKernelAvgMisorientations | 4 | 
| StatisticsPlugin | FindLocalAverageCAxisMisalignments | 7 | 
| StatisticsPlugin | FindMisorientations | 4 | 
| StatisticsPlugin | FindModulusMismatch | 2 | 
| StatisticsPlugin | FindNeighborhoods | 3 | 
| StatisticsPlugin | FindOrientationFieldCurl | 3 | 
| StatisticsPlugin | FindSchmids | 3 | 
| StatisticsPlugin | FindShapes | 2 | 
| StatisticsPlugin | FindSlipTransmissionMetrics | 4 | 
| StatisticsPlugin | FindSurfaceAreaToVolume | 2 | 
| StatisticsPlugin | FindTwinBoundaries | 5 | 
| StatisticsPlugin | FindTwinBoundarySchmidFactors | 6 | 
| StatisticsPlugin | FitCorrelatedFeatureData | 4 | 
| StatisticsPlugin | FitFeatureData | 3 | 
| StatisticsPlugin | GenerateEnsembleStatistics | 16 | 
| SurfaceMeshingPlugin | FeatureFaceCurvatureFilter | 4 | 
| SurfaceMeshingPlugin | FindBoundaryAreas | 2 | 
| SurfaceMeshingPlugin | FindGBCD | 6 | 
| SurfaceMeshingPlugin | GenerateFaceIPFColoring | 5 | 
| SurfaceMeshingPlugin | GenerateFaceMisorientationColoring | 4 | 
| SurfaceMeshingPlugin | GenerateFaceSchuhMisorientationColoring | 4 | 
| SurfaceMeshingPlugin | QuickSurfaceMesh | 2 | 
| SyntheticBuildingPlugin | EstablishMatrixPhase | 2 | 
| SyntheticBuildingPlugin | InitializeSyntheticVolume | 2 | 
| SyntheticBuildingPlugin | InsertPrecipitatePhases | 8 | 
| SyntheticBuildingPlugin | JumbleOrientations | 3 | 
| SyntheticBuildingPlugin | MatchCrystallography | 9 | 
| SyntheticBuildingPlugin | PackPrimaryPhases | 4 | 
| TransformationPhasePlugin | FindCSLBoundaries | 5 | 
| TransformationPhasePlugin | InsertTransformationPhases | 11 | 
| TransformationPhasePlugin | TiDwellFatigueCrystallographicAnalysis | 6 |

**Comment by sdonegan** [comment]
This issue has been addressed during the filter review leading up to v6. Any individual filters that may require additional modification should be submitted as single issues in the future.
