### ISSUE TITLE
Add ability to extract a pipeline from a .dream3d file

### ISSUE THREAD

**Issue by wlenthe** [dream3d/DREAM3D#232]
The pipeline would be whatever was run to create the file

**Comment by wlenthe** [comment]
This feature seems to suffer from the same bug as filters that take an input as degrees and convert to radians at runtime. For example if a dataset is created by running align sections (misorientation) with a 5 degree tolerance the extracted pipeline will have a tolerance of 0.087266.

**Comment by imikejackson** [comment]
If that is happening then it is an error on the part of the programmed. If you find specific examples please create a bug report for each filter (Or a single bug report listing all the filters that are affected).

**Comment by imikejackson** [comment]
Closing. Can not replicate
