### ISSUE TITLE
PhaseTypeSelection Widget does not send correct number of phases back to filter during preflight

### ISSUE THREAD

**Issue by imikejackson** [dream3d/DREAM3D#237]
The PhaseTypeSelectionWidget does not send back the proper phase count and phase types when preflight is run IF the attribute matrix was changed on the GUI. The reason is that the AttributeMatrix selection and the Phase Type selection are not in any way linked together and they really need to be. The number of Phase Type combo boxes is directly depended on the attribute matrix that was selected. this change needs to be communicated to the PhaseType Selection Widget before any preflight happens at all. 
 It is suggested that the PhaseTypeSelectionWidget incorporate the Attribute Matrix Selection Widget, and the PhaseTypeFilterParameter be updated accordingly to allow the programmer to set the Q_PROPERTY that sets the Attribute Matrix Path

**Comment by sdonegan** [comment]
Closed via ba361e1
