### ISSUE TITLE
Find Average Value of Scalars doesn't properly preflight / datacheck

### ISSUE THREAD

**Issue by wlenthe** [dream3d/DREAM3D#238]
-A boolean array can be selected and the filter reports an error message when run but reports no issues in preflight
-a vector array can be selected and run with no warnings / errors

**Comment by wlenthe** [comment]
Also the help file is just a copy of "Find Feature Average Orientations"

**Comment by sdonegan** [comment]
All documentation will be reviewed and updated for the version 5.2 release.  This is covered in issue #274, so this issue is being moved to done.
