### ISSUE TITLE
Searching for filters should be a word for word wild card search

### ISSUE THREAD

**Issue by imikejackson** [dream3d/DREAM3D#258]

**Comment by imikejackson** [comment]
When using the "Search" feature for filters the QLineEdit complete text is used as the wild card. for example if the user enters "Write DREAM3D" then the search will look for filters that contains  "Write DREAM3D" instead of looking for filters that contain "Write" AND "DREAM3D".

**Comment by imikejackson** [comment]
There may be some lingering qDebug() statements. Please clean up.

**Comment by joeykleingers** [comment]
Still need to create an API where each filter gets listed depending on how many words are matched.  Might need to use a QMap for this.  We can match with even more relevance if we keep track of which filters have the most words matched.
