### ISSUE TITLE
Array selection widget doesn't properly store state

### ISSUE THREAD

**Issue by wlenthe** [dream3d/DREAM3D#261]
If a pipeline contains an array selection widget the state is often not saved correctly when exiting / reopening dream3d. For example if some arrays or attribute matrices on 'Read DREAM3D Data' file are unticked and then dream3d closed/opened all boxes will be ticked again. This seems to also sometime happen when a pipeline is run (e.g. unticked boxes on 'Read DREAM3D Data' will become ticked or ticked boxes on 'Delete Data' will be cleared when 'Go' is pressed)

**Comment by joeykleingers** [comment]
Unable to replicate on Windows 8.1.  Please provide a clear sequence that will cause this bug.

**Comment by wlenthe** [comment]
I was able to reproduce this bug with the following pipeline by ticking SurfaceDataContainer | VertexData on the Delete Data filter (filter 20). The gui shows the box as ticked but the exported pipeline does not properly save the selection so it is cleared when dream3d is closed/reopened or the pipeline is loaded from a file. Similarly selecting individual arrays in SurfaceDataContainer | FaceData | required several attempts to export correctly.


[PipelineBuilder]
Name=DeleteDataBug
Number_Filters=22
Version=2015.03

[0]
Filter_Name=ReadH5Ebsd
Filter_Human_Label=Read H5Ebsd File
FilterVersion=2015.03.11
DataContainerName=VolumeDataContainer
CellAttributeMatrixName=CellData
CellEnsembleAttributeMatrixName=CellEnsembleData
InputFile=D:\\input.h5ebsd
RefFrameZDir=0
ZStartIndex=88
ZEndIndex=88
UseTransformations=1
ArraySelections_SelectedArrayNames\size=4
ArraySelections_SelectedArrayNames\1\SelectedArrayNames=EulerAngles
ArraySelections_SelectedArrayNames\2\SelectedArrayNames=Image Quality
ArraySelections_SelectedArrayNames\3\SelectedArrayNames=Phases
ArraySelections_SelectedArrayNames\4\SelectedArrayNames=Confidence Index

[1]
Filter_Name=FindCellQuats
Filter_Human_Label=Find Cell Quaternions
FilterVersion=2015.03.11
QuatsArrayName=Quats
CrystalStructuresArrayPath=VolumeDataContainer|CellEnsembleData|CrystalStructures
CellPhasesArrayPath=VolumeDataContainer|CellData|Phases
CellEulerAnglesArrayPath=VolumeDataContainer|CellData|EulerAngles

[2]
Filter_Name=EBSDSegmentFeatures
Filter_Human_Label=Segment Features (Misorientation)
FilterVersion=2015.03.11
CellFeatureAttributeMatrixName=CellFeatureData
ActiveArrayName=Active
FeatureIdsArrayName=FeatureIds
QuatsArrayPath=VolumeDataContainer|CellData|Quats
CrystalStructuresArrayPath=VolumeDataContainer|CellEnsembleData|CrystalStructures
CellPhasesArrayPath=VolumeDataContainer|CellData|Phases
GoodVoxelsArrayPath=VolumeDataContainer|CellData|
UseGoodVoxels=0
MisorientationTolerance=5

[3]
Filter_Name=FindAvgOrientations
Filter_Human_Label=Find Feature Average Orientations
FilterVersion=2015.03.11
AvgQuatsArrayPath=VolumeDataContainer|CellFeatureData|AvgQuats
AvgEulerAnglesArrayPath=VolumeDataContainer|CellFeatureData|AvgEulerAngles
CrystalStructuresArrayPath=VolumeDataContainer|CellEnsembleData|CrystalStructures
QuatsArrayPath=VolumeDataContainer|CellData|Quats
CellPhasesArrayPath=VolumeDataContainer|CellData|Phases
FeatureIdsArrayPath=VolumeDataContainer|CellData|FeatureIds

[4]
Filter_Name=FindFeaturePhases
Filter_Human_Label=Find Feature Phases
FilterVersion=2015.03.11
CellFeatureAttributeMatrixName=VolumeDataContainer|CellFeatureData|
FeaturePhasesArrayName=Phases
CellPhasesArrayPath=VolumeDataContainer|CellData|Phases
FeatureIdsArrayPath=VolumeDataContainer|CellData|FeatureIds

[5]
Filter_Name=InputCrystalCompliances
Filter_Human_Label=Input Crystal Compliances
FilterVersion=2015.03.11
CellEnsembleAttributeMatrixName=VolumeDataContainer|CellEnsembleData|
Compliances\size=3
Compliances\1\v11=0.764970004558563
Compliances\2\v12=-0.294333010911942
Compliances\3\v13=-0.294333010911942
Compliances\4\v14=0
Compliances\5\v15=0
Compliances\6\v16=0
Compliances\7\v22=0.764970004558563
Compliances\8\v23=-0.294333010911942
Compliances\9\v24=0
Compliances\10\v25=0
Compliances\11\v26=0
Compliances\12\v33=0.764970004558563
Compliances\13\v34=0
Compliances\14\v35=0
Compliances\15\v36=0
Compliances\16\v44=0.819671988487244
Compliances\17\v45=0
Compliances\18\v46=0
Compliances\19\v55=0.819671988487244
Compliances\20\v56=0
Compliances\21\v66=0.819671988487244
CrystalCompliancesArrayName=CrystalCompliances

[6]
Filter_Name=FindDirectionalModuli
Filter_Human_Label=Find Directional Moduli
FilterVersion=2015.03.11
LoadingDirection\size=3
LoadingDirection\1\x=0
LoadingDirection\2\y=1
LoadingDirection\3\z=0
FeaturePhasesArrayPath=VolumeDataContainer|CellFeatureData|Phases
AvgQuatsArrayPath=VolumeDataContainer|CellFeatureData|AvgQuats
CrystalStructuresArrayPath=VolumeDataContainer|CellEnsembleData|CrystalStructures
CrystalCompliancesArrayPath=VolumeDataContainer|CellEnsembleData|CrystalCompliances
DirectionalModuliArrayName=DirectionalModuli

[7]
Filter_Name=QuickSurfaceMesh
Filter_Human_Label=Quick Surface Mesh
FilterVersion=2015.03.11
SurfaceDataContainerName=SurfaceDataContainer
VertexAttributeMatrixName=VertexData
FaceAttributeMatrixName=FaceData
FacePhasesArrayName=SurfaceMeshFacePhases
NodeTypesArrayName=SurfaceMeshNodeType
FaceLabelsArrayName=SurfaceMeshFaceLabels
CellPhasesArrayPath=||
FeatureIdsArrayPath=VolumeDataContainer|CellData|FeatureIds
TransferPhaseId=0

[8]
Filter_Name=DataContainerWriter
Filter_Human_Label=Write DREAM3D Data File
FilterVersion=2015.03.11
OutputFile=D:\\meshed.dream3d
WriteXdmfFile=1

[9]
Filter_Name=GenerateFaceSchuhMisorientationColoring
Filter_Human_Label=Generate Face Schuh Misorientation Colors
FilterVersion=2015.03.11
SurfaceMeshFaceSchuhMisorientationColorsArrayName=SurfaceMeshFaceSchuhMisorientationColors
CrystalStructuresArrayPath=VolumeDataContainer|CellEnsembleData|CrystalStructures
FeaturePhasesArrayPath=VolumeDataContainer|CellFeatureData|Phases
AvgQuatsArrayPath=VolumeDataContainer|CellFeatureData|AvgQuats
SurfaceMeshFaceLabelsArrayPath=SurfaceDataContainer|FaceData|SurfaceMeshFaceLabels

[10]
Filter_Name=FindModulusMismatch
Filter_Human_Label=Find Elastic Modulus Mismatch
FilterVersion=2015.03.11
SurfaceMeshDeltaModulusArrayName=SurfaceMeshDeltaModulus
SurfaceMeshFaceLabelsArrayPath=SurfaceDataContainer|FaceData|SurfaceMeshFaceLabels
ModuliArrayPath=VolumeDataContainer|CellFeatureData|DirectionalModuli

[11]
Filter_Name=TriangleAreaFilter
Filter_Human_Label=Generate Triangle Areas
FilterVersion=2015.03.11
FaceAttributeMatrixName=SurfaceDataContainer|FaceData|
SurfaceMeshTriangleAreasArrayName=SurfaceMeshFaceAreas

[12]
Filter_Name=SharedFeatureFaceFilter
Filter_Human_Label=Generate Triangle Face Ids
FilterVersion=2015.03.11
FaceFeatureAttributeMatrixName=FaceFeatureData
SurfaceMeshFeatureFaceIdsArrayName=SurfaceMeshFeatureFaceId
SurfaceMeshFeatureFaceLabelsArrayName=SurfaceMeshFaceLabels
SurfaceMeshFeatureFaceNumTrianglesArrayName=NumTriangles
SurfaceMeshFaceLabelsArrayPath=SurfaceDataContainer|FaceData|SurfaceMeshFaceLabels

[13]
Filter_Name=FindTwinBoundaries
Filter_Human_Label=Find Twin Boundaries
FilterVersion=2015.03.11
SurfaceMeshTwinBoundaryIncoherenceArrayName=SurfaceMeshTwinBoundaryIncoherence
SurfaceMeshCoherentFaceNormalsArrayName=SurfaceCoherentMeshFaceNormals
SurfaceMeshTwinBoundaryArrayName=SurfaceMeshTwinBoundary
SurfaceMeshFaceNormalsArrayPath=||
SurfaceMeshFaceLabelsArrayPath=SurfaceDataContainer|FaceFeatureData|SurfaceMeshFaceLabels
CrystalStructuresArrayPath=VolumeDataContainer|CellEnsembleData|CrystalStructures
FeaturePhasesArrayPath=VolumeDataContainer|CellFeatureData|Phases
AvgQuatsArrayPath=VolumeDataContainer|CellFeatureData|AvgQuats
AxisTolerance=5
AngleTolerance=5
FindCoherence=0
FindCoherentNormals=0

[14]
Filter_Name=FindBoundaryAreas
Filter_Human_Label=Find Face Feature Boundary Areas
FilterVersion=2015.03.11
FaceFeatureAttributeMatrixPath=SurfaceDataContainer|FaceFeatureData|
SurfaceMeshTriangleAreasArrayPath=SurfaceDataContainer|FaceData|SurfaceMeshFaceAreas
SurfaceMeshFeatureFaceIdsArrayPath=SurfaceDataContainer|FaceData|SurfaceMeshFeatureFaceId
SurfaceMeshBoundaryAreasArrayName=BoundaryAreas

[15]
Filter_Name=FindCoherentTwinNormals
Filter_Human_Label=Find Coherent Twin Normals
FilterVersion=2015.03.11
SurfaceMeshCoherentFaceNormalsArrayName=SurfaceMeshCoherentFaceNormals
SurfaceMeshFaceLabelsArrayPath=SurfaceDataContainer|FaceFeatureData|SurfaceMeshFaceLabels
SurfaceMeshTwinBoundaryArrayPath=SurfaceDataContainer|FaceFeatureData|SurfaceMeshTwinBoundary
CrystalStructuresArrayPath=VolumeDataContainer|CellEnsembleData|CrystalStructures
FeaturePhasesArrayPath=VolumeDataContainer|CellFeatureData|Phases
AvgQuatsArrayPath=VolumeDataContainer|CellFeatureData|AvgQuats

[16]
Filter_Name=CopyFeatureArrayToCellArray
Filter_Human_Label=Create Cell Array From Feature Array
FilterVersion=2015.03.11
FeatureIdsArrayPath=SurfaceDataContainer|FaceData|SurfaceMeshFeatureFaceId
SelectedFeatureArrayPath=SurfaceDataContainer|FaceFeatureData|SurfaceMeshCoherentFaceNormals
CreatedArrayName=coherentnormals

[17]
Filter_Name=CopyFeatureArrayToCellArray
Filter_Human_Label=Create Cell Array From Feature Array
FilterVersion=2015.03.11
FeatureIdsArrayPath=SurfaceDataContainer|FaceData|SurfaceMeshFeatureFaceId
SelectedFeatureArrayPath=SurfaceDataContainer|FaceFeatureData|SurfaceMeshTwinBoundary
CreatedArrayName=twinboundary

[18]
Filter_Name=FindTwinBoundaries
Filter_Human_Label=Find Twin Boundaries
FilterVersion=2015.03.11
SurfaceMeshTwinBoundaryIncoherenceArrayName=SurfaceMeshTwinBoundaryIncoherence
SurfaceMeshCoherentFaceNormalsArrayName=SurfaceMeshFaceNormals
SurfaceMeshTwinBoundaryArrayName=SurfaceMeshTwinBoundary2
SurfaceMeshFaceNormalsArrayPath=SurfaceDataContainer|FaceFeatureData|SurfaceMeshCoherentFaceNormals
SurfaceMeshFaceLabelsArrayPath=SurfaceDataContainer|FaceFeatureData|SurfaceMeshFaceLabels
CrystalStructuresArrayPath=VolumeDataContainer|CellEnsembleData|CrystalStructures
FeaturePhasesArrayPath=VolumeDataContainer|CellFeatureData|Phases
AvgQuatsArrayPath=VolumeDataContainer|CellFeatureData|AvgQuats
AxisTolerance=5
AngleTolerance=5
FindCoherence=1
FindCoherentNormals=0

[19]
Filter_Name=CopyFeatureArrayToCellArray
Filter_Human_Label=Create Cell Array From Feature Array
FilterVersion=2015.03.11
FeatureIdsArrayPath=SurfaceDataContainer|FaceData|SurfaceMeshFeatureFaceId
SelectedFeatureArrayPath=SurfaceDataContainer|FaceFeatureData|SurfaceMeshTwinBoundaryIncoherence
CreatedArrayName=coherence

[20]
Filter_Name=RemoveArrays
Filter_Human_Label=Delete Data
FilterVersion=2015.03.11
DataArraysToRemove\size=31
DataArraysToRemove\1\Path=VolumeDataContainer|CellData|Confidence Index
DataArraysToRemove\1\DCFlag=2
DataArraysToRemove\1\ATTRFlag=0
DataArraysToRemove\1\DAFlag=0
DataArraysToRemove\2\Path=VolumeDataContainer|CellData|EulerAngles
DataArraysToRemove\2\DCFlag=2
DataArraysToRemove\2\ATTRFlag=0
DataArraysToRemove\2\DAFlag=0
DataArraysToRemove\3\Path=VolumeDataContainer|CellData|FeatureIds
DataArraysToRemove\3\DCFlag=2
DataArraysToRemove\3\ATTRFlag=0
DataArraysToRemove\3\DAFlag=0
DataArraysToRemove\4\Path=VolumeDataContainer|CellData|Image Quality
DataArraysToRemove\4\DCFlag=2
DataArraysToRemove\4\ATTRFlag=0
DataArraysToRemove\4\DAFlag=0
DataArraysToRemove\5\Path=VolumeDataContainer|CellData|Phases
DataArraysToRemove\5\DCFlag=2
DataArraysToRemove\5\ATTRFlag=0
DataArraysToRemove\5\DAFlag=0
DataArraysToRemove\6\Path=VolumeDataContainer|CellData|Quats
DataArraysToRemove\6\DCFlag=2
DataArraysToRemove\6\ATTRFlag=0
DataArraysToRemove\6\DAFlag=0
DataArraysToRemove\7\Path=VolumeDataContainer|CellEnsembleData|CrystalCompliances
DataArraysToRemove\7\DCFlag=2
DataArraysToRemove\7\ATTRFlag=0
DataArraysToRemove\7\DAFlag=0
DataArraysToRemove\8\Path=VolumeDataContainer|CellEnsembleData|CrystalStructures
DataArraysToRemove\8\DCFlag=2
DataArraysToRemove\8\ATTRFlag=0
DataArraysToRemove\8\DAFlag=0
DataArraysToRemove\9\Path=VolumeDataContainer|CellEnsembleData|LatticeConstants
DataArraysToRemove\9\DCFlag=2
DataArraysToRemove\9\ATTRFlag=0
DataArraysToRemove\9\DAFlag=0
DataArraysToRemove\10\Path=VolumeDataContainer|CellEnsembleData|MaterialName
DataArraysToRemove\10\DCFlag=2
DataArraysToRemove\10\ATTRFlag=0
DataArraysToRemove\10\DAFlag=0
DataArraysToRemove\11\Path=VolumeDataContainer|CellFeatureData|Active
DataArraysToRemove\11\DCFlag=2
DataArraysToRemove\11\ATTRFlag=0
DataArraysToRemove\11\DAFlag=0
DataArraysToRemove\12\Path=VolumeDataContainer|CellFeatureData|AvgEulerAngles
DataArraysToRemove\12\DCFlag=2
DataArraysToRemove\12\ATTRFlag=0
DataArraysToRemove\12\DAFlag=0
DataArraysToRemove\13\Path=VolumeDataContainer|CellFeatureData|AvgQuats
DataArraysToRemove\13\DCFlag=2
DataArraysToRemove\13\ATTRFlag=0
DataArraysToRemove\13\DAFlag=0
DataArraysToRemove\14\Path=VolumeDataContainer|CellFeatureData|DirectionalModuli
DataArraysToRemove\14\DCFlag=2
DataArraysToRemove\14\ATTRFlag=0
DataArraysToRemove\14\DAFlag=0
DataArraysToRemove\15\Path=VolumeDataContainer|CellFeatureData|Phases
DataArraysToRemove\15\DCFlag=2
DataArraysToRemove\15\ATTRFlag=0
DataArraysToRemove\15\DAFlag=0
DataArraysToRemove\16\Path=SurfaceDataContainer|FaceData|SurfaceMeshDeltaModulus
DataArraysToRemove\16\DCFlag=0
DataArraysToRemove\16\ATTRFlag=0
DataArraysToRemove\16\DAFlag=2
DataArraysToRemove\17\Path=SurfaceDataContainer|FaceData|SurfaceMeshFaceAreas
DataArraysToRemove\17\DCFlag=0
DataArraysToRemove\17\ATTRFlag=0
DataArraysToRemove\17\DAFlag=2
DataArraysToRemove\18\Path=SurfaceDataContainer|FaceData|SurfaceMeshFaceLabels
DataArraysToRemove\18\DCFlag=0
DataArraysToRemove\18\ATTRFlag=0
DataArraysToRemove\18\DAFlag=2
DataArraysToRemove\19\Path=SurfaceDataContainer|FaceData|SurfaceMeshFaceSchuhMisorientationColors
DataArraysToRemove\19\DCFlag=0
DataArraysToRemove\19\ATTRFlag=0
DataArraysToRemove\19\DAFlag=2
DataArraysToRemove\20\Path=SurfaceDataContainer|FaceData|SurfaceMeshFeatureFaceId
DataArraysToRemove\20\DCFlag=0
DataArraysToRemove\20\ATTRFlag=0
DataArraysToRemove\20\DAFlag=2
DataArraysToRemove\21\Path=SurfaceDataContainer|FaceData|coherence
DataArraysToRemove\21\DCFlag=0
DataArraysToRemove\21\ATTRFlag=0
DataArraysToRemove\21\DAFlag=0
DataArraysToRemove\22\Path=SurfaceDataContainer|FaceData|coherentnormals
DataArraysToRemove\22\DCFlag=0
DataArraysToRemove\22\ATTRFlag=0
DataArraysToRemove\22\DAFlag=0
DataArraysToRemove\23\Path=SurfaceDataContainer|FaceData|twinboundary
DataArraysToRemove\23\DCFlag=0
DataArraysToRemove\23\ATTRFlag=0
DataArraysToRemove\23\DAFlag=0
DataArraysToRemove\24\Path=SurfaceDataContainer|FaceFeatureData|BoundaryAreas
DataArraysToRemove\24\DCFlag=0
DataArraysToRemove\24\ATTRFlag=0
DataArraysToRemove\24\DAFlag=0
DataArraysToRemove\25\Path=SurfaceDataContainer|FaceFeatureData|NumTriangles
DataArraysToRemove\25\DCFlag=0
DataArraysToRemove\25\ATTRFlag=0
DataArraysToRemove\25\DAFlag=0
DataArraysToRemove\26\Path=SurfaceDataContainer|FaceFeatureData|SurfaceMeshCoherentFaceNormals
DataArraysToRemove\26\DCFlag=0
DataArraysToRemove\26\ATTRFlag=0
DataArraysToRemove\26\DAFlag=0
DataArraysToRemove\27\Path=SurfaceDataContainer|FaceFeatureData|SurfaceMeshFaceLabels
DataArraysToRemove\27\DCFlag=0
DataArraysToRemove\27\ATTRFlag=0
DataArraysToRemove\27\DAFlag=0
DataArraysToRemove\28\Path=SurfaceDataContainer|FaceFeatureData|SurfaceMeshTwinBoundary
DataArraysToRemove\28\DCFlag=0
DataArraysToRemove\28\ATTRFlag=0
DataArraysToRemove\28\DAFlag=0
DataArraysToRemove\29\Path=SurfaceDataContainer|FaceFeatureData|SurfaceMeshTwinBoundary2
DataArraysToRemove\29\DCFlag=0
DataArraysToRemove\29\ATTRFlag=0
DataArraysToRemove\29\DAFlag=0
DataArraysToRemove\30\Path=SurfaceDataContainer|FaceFeatureData|SurfaceMeshTwinBoundaryIncoherence
DataArraysToRemove\30\DCFlag=0
DataArraysToRemove\30\ATTRFlag=0
DataArraysToRemove\30\DAFlag=0
DataArraysToRemove\31\Path=SurfaceDataContainer|VertexData|SurfaceMeshNodeType
DataArraysToRemove\31\DCFlag=0
DataArraysToRemove\31\ATTRFlag=0
DataArraysToRemove\31\DAFlag=0

[21]
Filter_Name=DataContainerWriter
Filter_Human_Label=Write DREAM3D Data File
FilterVersion=2015.03.11
OutputFile=D:\\output.dream3d
WriteXdmfFile=1

**Comment by imikejackson** [comment]
Closing. Can not replicate.
