### ISSUE TITLE
FindDirectionalModuli filter includes Eigen header even when DREAM3D is built without Eigen

### ISSUE THREAD

**Issue by sdonegan** [dream3d/DREAM3D#265]
The FindDirectionalModuli filter in the Statistics plugin requires Eigen to function, yet it is still included in the build when Eigen is not available, which will prevent compilation.  A CMake check is needed to ensure that FindDirectionalModuli is not included in the build when Eigen is unavailable.

**Comment by joeykleingers** [comment]
This bug doesn't matter any more because we now require Eigen.
