### ISSUE TITLE
Read Ensemble Info File creates junk data

### ISSUE THREAD

**Issue by wlenthe** [dream3d/DREAM3D#282]
Read Ensemble Info File creates an ensemble attribute matrix with dimension 1 + 'number of phases read' (EnsembleInfoReader.cpp line 237) but then only writes data once for each phase, leaving junk data in the last entry. The filter should either create an attribute matrix of dimension 'number of phases read' and fill it in using the read data or create an attribute matrix of dimension 1 + 'number of phases read', write a 'bad' phase to the first spot (UnknownCrystalStructure /UnknownPhaseType) and then write the read data to indices 1 -> 1 + 'number of phases read'

**Comment by imikejackson** [comment]
Do you have an example ensemble file that is causing problems.
