### ISSUE TITLE
Clear Data (Mask) Missing input parameters

### ISSUE THREAD

**Issue by imikejackson** [dream3d/DREAM3D#294]
Processing Plugin filter "Clear Data (Mask)" does not present the user with the correct number of filter inputs according to the documentation.

**Comment by sdonegan** [comment]
This was an oversight when Mike G.  was updating documentation in the Processing plugin.  The filter itself is fine, but shared a similar name with a different filter.  The documentation was moved around, and the incorrect documentation file was left in.  Mike G. will fix this issue and send a pull request when fixed.

**Comment by sdonegan** [comment]
This issue has been fixed with commit 7deba8e32f72d90ebf059b6a8785292174c97d1e to the main DREAM3D repo.
