### ISSUE TITLE
Help in converting vtk to Abaqus .inp file

### ISSUE THREAD

**Issue by antilog** [dream3d/DREAM3D#316]
I am new to Dream 3D. I was able to create pipeline and get vtk output file to view using Paraview. How do I get the 3-D co-ordinates of the nodes using python? Could someone please share the script ? Thanks!

**Comment by imikejackson** [comment]
In the latest versions of DREAM3D (Posted nightly to dream3d.bluequartz.net/binaries/experimental/) there is a new filter that can generate a set of Abaqus files that are based off the voxels of the data. Give that a try and let us know if it works for you.
