### ISSUE TITLE
Update PluginMaker template with new include statements and fix general inconsistencies.

### ISSUE THREAD

**Issue by joeykleingers** [dream3d/DREAM3D#318]

**Comment by joeykleingers** [comment]
When this branch gets merged into develop, we need to commit and push some code to the other external plugin repos for the entire program to be able to compile.  If this gets merged into develop and we leave the other repos the way they are, THIS WILL NOT COMPILE.

**Comment by imikejackson** [comment]
Combine interface into a single window with a Tabbed interface.

Add a QSplitter for FilterMaker tab for FilterMaker.

After merging in branch #312,  using the new DREAM3D Custom QSplitter class.
