### ISSUE TITLE
Add feature to allow PluginMaker to create a base filter inside an existing plugin

### ISSUE THREAD

**Issue by imikejackson** [dream3d/DREAM3D#319]
Developers need an easier way to create a new blank filter filled with skeleton code. Add a feature to PluginMaker that creates the filter files and Documentation files inside an existing plugin directory. The user would be required to update the "sourcelist.cmake" file with the new filter. 

Bonus points for having the program update the sourcelist.cmake file correctly. There is example code in the Tools/FilterParameterTool.cpp file that shows how to use Qt to read/parse/replace and write a file back out.

**Comment by imikejackson** [comment]
Developers need an easier way to create a new blank filter filled with skeleton code. Add a feature to PluginMaker that creates the filter files and Documentation files inside an existing plugin directory. The user would be required to update the "sourcelist.cmake" file with the new filter. 

Bonus points for having the program update the sourcelist.cmake file correctly. There is example code in the Tools/FilterParameterTool.cpp file that shows how to use Qt to read/parse/replace and write a file back out.

**Comment by joeykleingers** [comment]
This issue has been migrated over to issue #318.
