### ISSUE TITLE
Can not append Filter Parameters to a group when writing a pipeline file or pipeline into a dream3d file.

### ISSUE THREAD

**Issue by imikejackson** [dream3d/DREAM3D#333]
This issue will raise when a filter subclass calls its super class to write its values, then it writes its own values. The first set of value will be over written. Look at the Reconstruction/MergeTwins filter for an example. The INI and .dream3d files need to be updated. The JSON filter parameter writer has been updated. 
  Also look at the readers to make sure they also behave correctly.

**Comment by joeykleingers** [comment]
This seems to be fixed in both INI and DREAM3D formats.  Unable to replicate issue.
