### ISSUE TITLE
Absolute value changes

### ISSUE THREAD

**Issue by leavy** [dream3d/DREAM3D#374]
Mike, et al.
I was getting some compiler warnings in 
Source/OrientationLib/OrientationMath/OrientationTransforms.hpp and FindNeighborhoods.cpp
and Source/Plugins/Statistics/StatisticsFilters/FindNeighborhoods.cpp when building.  
So I tried to fix the absolute values used to the proper namespace,  but it appeared that I didn't have permission to push the files back to the develop repository.  I can send the files to you if you like.

Thanks,
Brian Leavy

**Comment by sdonegan** [comment]
Hi Brian,
Were you compiling on Linux? I can take a look on that system and get the warnings fixed up. The easiest way to handle getting fixes you make back into the main repo is to "fork" the DREAM.3D repo into your own GitHub area. You can then submit a "pull request" if you want to get any of your stuff merged in. Mike Groeber has been using this approach to great effect, and I'm sure he'd be happy to help with any questions on using the fork & pull system.

thanks,
-Sean

**Comment by leavy** [comment]
Thanks Sean,
This on a macbook pro using Homebrew.
I was using SourceTree per Mike Jackson's previous recommendations.  I think it is a "clone" versus a "fork", but I'm not as comfortable with GIT as I was with SVN.  It gave me a permission denied error #403
when trying to push back to the github develop repository.

**Comment by imikejackson** [comment]
Brian, 
    Is this with GCC under homebrew? We do not see these warnings with clang on OS X.

**Comment by leavy** [comment]
I believe it was with gcc under homebrew.  I've created a fork now, and am making sure it builds OK.  I see the pull request button above.  So, I'll try pushing it to my forked repository so you can see the files and decide if it's worth changing?  It was just warnings of possible integer abs value functions on floats.

**Comment by leavy** [comment]
I think I successfully created a pull request on a fork of dream3d develop.  I pushed the two filter files that I changed.
