### ISSUE TITLE
Find Euclidean Distance Map filter does not properly compute Euclidean distances

### ISSUE THREAD

**Issue by sdonegan** [dream3d/DREAM3D#376]
The Find Euclidean Distance Map filter properly computes the Manhattan distances, but the Euclidean distances have a gradation along a particular axis. This is very clear when calculating both Manhattan and Euclidean, then in ParaView thresholding as Manhattan = 0 (to show the boundaries), then coloring by the Euclidean distance.

Thanks to A. Rovinelli for noticing this.

**Comment by imikejackson** [comment]
Fixed with Pull request #381
