### ISSUE TITLE
GBCD Doesn't Handle Two Phase Datasets (Creating and Visualizing)

### ISSUE THREAD

**Issue by mgroeber** [dream3d/DREAM3D#378]
The calculation of the GBCD bin each triangle belongs to is correct and handles the multiphase issue, but when the triangles are actually placed in the GBCD array, they are not checked to determine which ensemble/phase GBCD they should contribute to.  Fixing this in the GBCD calculation filter will also require updating of the visualization filters.

**Comment by sdonegan** [comment]
Fixed with commit d8857e1d91da133bc96ded7175327912f784bc25
