### ISSUE TITLE
Add option to Import Orientation Data to Create the DataContainer in addition to creating the .h5ebsd file

### ISSUE THREAD

**Issue by imikejackson** [dream3d/DREAM3D#4]
In order to read EBSD Orientation data the user must first convert the data into an H5EBSD file, then clear the pipeline and read the h5ebsd file using a new filter. 

We should just create the data container with all the data from the Orientation files then give the user the option to write out an H5EBSD file or go ahead with more DREAM3D Filters

**Comment by joeykleingers** [comment]
Too complicated to implement, due to the need to combine two complicated user interfaces and have one filter take on the duties of both the Import Orientation File(s) to H5Ebsd and Read H5Ebsd File filters.
