### ISSUE TITLE
Crop Volume Filter does not properly update its GUI when the data container changes.

### ISSUE THREAD

**Issue by imikejackson** [dream3d/DREAM3D#423]
The Crop Volume filter uses a VolumeInfoWidget to display the resolution and dimensions of an Image Data container. The information is not properly updated when the user changes the data container. The issue lies in the methods in the Crop Volume filter that retrieve the dimensions and resolution to be displayed. The Attribute Matrix path is used for the path information.

I am not sure this widget is needed anymore as the same information can be found on the "Current Data Structure" tab of the filter input.

**Comment by mgroeber** [comment]
I would agree with the assessment that the widget is not necessary with the advent of the much more helpful current structure tab
