### ISSUE TITLE
Add filter to append additional Slice of data to Image Geometry

### ISSUE THREAD

**Issue by imikejackson** [dream3d/DREAM3D#433]
A filter is needed that will resize an Image Geometry by adding a slice in the Z direction. The filter will ensure the AttributeMatrix and all AttributeArrays are properly resized and initialized with proper data.

This filter is very specific for adding slice of data in the Z direction. Eventually this filter can be extended to enlarge in any direction but for now this is the basic functionality that is needed for the LEROY2 project.

**Comment by imikejackson** [comment]
Commit 16ea398af8f1c23896d08725cfaa5e315297e71e updates this issue.

**Comment by sdonegan** [comment]
Closing with implementation of AppendImageGeometryZSlice.
