### ISSUE TITLE
Use Recommended Transformations Bug

### ISSUE THREAD

**Issue by frombs** [dream3d/DREAM3D#470]
When selecting the "Use Recommended Transformation" option within the "Read H5EBSD File" filter, the X-position and Z-position values become corrupt.  This was verified by outputting a dream.3d file after running the filter and viewing the data in HDFView (or in ParaView).  In my case, the values of X-position were replaced by the max value of X.  Also, in ParaView the X and Z bounds contain negative values.  I am running Version 6.2 of the software with OSX 10.10.5.

**Comment by imikejackson** [comment]
Is this with a standard pipeline or a custom pipeline that you have created? I am unable to reproduce this issue. When viewing in HDFView one has to be cognizant that HDFView can only show 2D slices of data through the 3D data set. This means that by default HDFView shows the X Values in the ZY plane. If you right click on the data set in HDFView and select "Open As", the select the "SpreadSheet", then adjust the dimensions that will be show to be Dims=1 and Dims=2, the expected X Values will show up. I also took a look in ParaView and the X & Y Values were all positive. 
   Again this was for a simple data set import of the IN100 from ANG files to H5EBSD, then from H5EBSD to .dream3d.

**Comment by imikejackson** [comment]
User's need to add the "Change Origin/Resolution" filter to reset the origin back to 0,0,0 after using a transformation.
