### ISSUE TITLE
Align Sections (Mutual Information) Crash in V6.2

### ISSUE THREAD

**Issue by frombs** [dream3d/DREAM3D#472]
The "Align Sections (Mutual Information)" filter causes Dream3D V6.2 (OSX 10.10.5) to unexpectedly terminate if more than 2 slices of data are provided.  The auto-generated crash report lists the Exception Type as "EXC_BAD_ACCESS (SIGSEGV)" and the Exception Code as "KERN_INVALID_ADDRESS at 0x00006081fd7d4d28."  Let me know if you need the entire report.

**Comment by frombs** [comment]
Mike, I have verified that the fix works for my large dataset.  Thanks again for your help.

**Comment by imikejackson** [comment]
We can put in another issue to optimize the filter but I am going to close this issue.

**Comment by frombs** [comment]
I think I figured out why it was so slow.  My threshold tolerance for confidence index was set to 0.  After increased the value, it only took about 5-10 minutes to run the filter.
