### ISSUE TITLE
Add a filter implementing the metric-based approach for computing GB distributions

### ISSUE THREAD

**Issue by kglowins** [dream3d/DREAM3D#473]
The approach is described in http://link.springer.com/article/10.1007%2Fs11661-014-2325-y

**Comment by kglowins** [comment]
I have created the first version of this filter (https://github.com/dream3d/DREAM3D/pull/496)

**Comment by sdonegan** [comment]
Closed via 3c250836c08e30c28ce99aa72228f4cc0e6c366f
