### ISSUE TITLE
Read H5EBSD Filter does not read start/end indices correctly from JSON file

### ISSUE THREAD

**Issue by sdonegan** [dream3d/DREAM3D#474]
The Read H5EBSD Filter does not seem to read its filter parameter for the start/end indices correctly from a saved pipeline file.  For example, when using the small IN100 data set, despite having the start index = 1 and end index = 117 in the JSON file, the Filter will set the values to 1 for the start and 99 for the end after reading from a pipeline file.

**Comment by imikejackson** [comment]
I just noticed this yesterday and will take a look.
