### ISSUE TITLE
Import Orientation File(s) to H5EBSD does not properly save angle conversion to JSON file

### ISSUE THREAD

**Issue by sdonegan** [dream3d/DREAM3D#475]
The Import Orientation File(s) to H5EBSD does not save whether the user has selected the convert orientations to radians checkbox in the reference frame dialogue to a JSON file.  This can cause confusion when reloading a pipeline that begins with this filter.

**Comment by imikejackson** [comment]
The original intent of that setting was just purely for visualizing the data in order to select the proper transformations. Currently the setting is not an actual filter parameter because it was just for visualization and had no effect on the import of the data.
