### ISSUE TITLE
VisualizeGBCDGMT.cpp - Normalization of the misorientation axis

### ISSUE THREAD

**Issue by kglowins** [dream3d/DREAM3D#477]
The part of code which converts a misorientation from its axis/angle representation into a matrix looks like this:

```cpp
float misAngle = m_MisorientationRotation.angle * SIMPLib::Constants::k_PiOver180;
// convert axis angle to matrix representation of misorientation
FOrientArrayType om(9);
FOrientTransformsType::ax2om(FOrientArrayType(m_MisorientationRotation.h, m_MisorientationRotation.k, m_MisorientationRotation.l, misAngle), om);
```

Don't we need to normalize the vector representing the misorientation axis before the conversion?

Using the above code, when I input the Sigma 9 misorientation (38.94deg about [110]), the matrix after conversion is:

1.0000 0.2222 0.6285
0.2222 1.0000 -0.6285
-0.6285 0.6285 0.7778,

and this does not look like a matrix corresponding to the Sigma 9 misorientation.

If I modify the code as follows:

```cpp
float norm = sqrtf(
		  m_MisorientationRotation.h * m_MisorientationRotation.h +
		  m_MisorientationRotation.k * m_MisorientationRotation.k +
		  m_MisorientationRotation.l * m_MisorientationRotation.l);

FOrientTransformsType::ax2om(FOrientArrayType(m_MisorientationRotation.h / norm, m_MisorientationRotation.k / norm, m_MisorientationRotation.l / norm, misAngle), om);
```

it gives the matrix:
0.8889 0.1111 0.4444
0.1111 0.8889 -0.4444
-0.4444 0.4444 0.7778,

which is the one I would expect.
 
The same problem occurs in VisualizeGBCDPoleFigure.cpp

**Comment by sdonegan** [comment]
Yes, you are correct, Krzysztof, thanks for the heads up!  The bug was introduced when we made a transition to a different framework for our orientation transformations (in the original transformation, the axis was normalized within the function that converted the axis-angle to an orientation matrix).  I will make the necessary fixes in the GBCD export filters and push them up shortly.
