### ISSUE TITLE
Rotate Sample Reference Frame Modifies Geometry

### ISSUE THREAD

**Issue by wlenthe** [dream3d/DREAM3D#506]
Currently the filter 'Rotate Sample Reference Frame' changes the gemoetry of the parent data container to match the new dimensions of the rotated cell attribute matrix but does not account for the case of multiple cell attribute matrices. This results in a mismatch that inevitably causes issues with subsequent filters. For example the following simple pipeline:
-Read H5EBSD
-Copy Attribute Matrix: ImageDataContainer::CellData->ImageDataContainer::CellDataRot
-Rotate Sample Reference Frame: ImageDataContainer::CellDataRot 45 @ 001
results in 2 cell data attribute matrices with different x/y dimensions in a single data container (with a geometry matching the rotated one). Limiting data containers to a single cell type attribute matrix or geometry would fix the problem but seems overly restrictive (e.g. for multi-modal datasets or time steps with changing geometries). One possible solution is moving the geometry from the data container to the attribute matrix level.

**Comment by sdonegan** [comment]
The current intent behind data containers is that they contain a single, unique geometry.  It will therefore be a requirement (in the future, not at the present) that a given data container only have a single attribute matrix for any given unit element, since the geometry for a given data container is static.  If the geometry changes, then this represents a new data container.  Several efforts will begin in the near future that will address some of the current limitations this structure has with multi-modal/time series data, including more concrete linkages between geometries and data containers.

**Comment by mgroeber** [comment]
I agree with limiting a single geometry to a data container.  While not strictly implemented in code, it has always been the intent to have, at most, only one of each unit element AM per data container.  There has been a lot of discussion and planning to create structures that will deal better with time series/multimodal datasets and hopefully implementation will begin soon.  The way I think of a data container is it is the container that holds the digital representation of an instance of a microstructural unit.  The definition of instance here accounts for real time, processing time, perspective, observation mechanism, etc.  So, rotating a data set is viewing the same microstructural unit, but from a different perspective.  Up- or down-sampling the grid/mesh is a step in processing time.  Keeping the mesh, but evolving the actual structure is a step in real (or simulation time).  Multimodal data (if not collected in a co-collection mode) are different observations of the same microstructural unit, but likely have different perspectives and resolutions of the unit.  
This may seem fairly strict, but with all the things that can be done to 3D digital data, it seems useful and pragmatic to define fundamental elements/classes that help to keep things organized and clear.

**Comment by sdonegan** [comment]
This issue will be addressed by enforcing element attribute matrix limitations at the DataContainer level.
