### ISSUE TITLE
Move Data filter 'improperly' assumes the same Attribute matrix

### ISSUE THREAD

**Issue by mgroeber** [dream3d/DREAM3D#507]
In the move data filter, if you try to move an attribute array from one AM to another AM with the same name, an error is created stating the AMs are the same and you probably selected the wrong AM.  This seems reasonable, but there could be two AMs with the same name in different DCs.  If the DCs share the same geometry then the number of tuples, in say the CellData AM, would match and arrays could be moved between the two CellData AMs, but this currently flags an error.  Seems the fix should just be to check the whole path to the AMs, not just the AM name.

**Comment by imikejackson** [comment]
I can fix this or did you want to submit a patch?
