### ISSUE TITLE
Refactor IGeometry classes by consolidating member variables

### ISSUE THREAD

**Issue by sdonegan** [dream3d/DREAM3D#522]
The IGeometry classes currently share many bits of code, but these were explicitly left out of IGeometry and implemented in  #includes as a hackish way to reduce code length and prevent new classes from overriding those functions.

With C++11, virtual functions can me marked as final to prevent overriding from child classes.  IGeometry classes can be moved to use this approach, which will significantly reduce code repetition and prevent child classes from shadowing or overriding functions they are not supposed to implement.

**Comment by joeykleingers** [comment]
All functions from the SharedGeometryOps source file have been moved to the IGeometry class, and are now shared via inheritance with all the IGeometry subclasses.

**Comment by imikejackson** [comment]
Merging current work into SIMPL repository.
