### ISSUE TITLE
Json pipelines/bookmarks do not list filters in pipeline order

### ISSUE THREAD

**Issue by joeykleingers** [dream3d/DREAM3D#530]

**Comment by joeykleingers** [comment]
Json bookmarks do not write their filters in pipeline order.  Filter 1 is next to Filter 10, which is next to Filter 100, etc.  We need to implement a digit padding system so that if there are 100 filters, the order would be 001, 002, 003, 004....

**Comment by imikejackson** [comment]
closed with commit d5bb1ed894185af236c7a90bc7ec1a0c5d2ae1ee at http://github.com/bluequartzsoftware/SIMPL
